import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ta'));
  }

  static const List<Locale> supportedLocales = [
    Locale('ta'),
    Locale('te'),
    Locale('kn'),
    Locale('ml'),
    Locale('en'),
  ];

  static const Map<String, String> languageNativeNames = {
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'kn': 'ಕನ್ನಡ',
    'ml': 'മലയാളം',
    'en': 'English',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Maruthamann',
      'tagline': 'Smart Farm Records for South Indian Farmers',
      'select_language': 'Select Language',
      'select_language_subtitle': 'Choose your preferred regional language to continue',
      'step_1_indicator': 'STEP 1 OF 2 · MOBILE AUTH',
      'step_2_indicator': 'STEP 2 OF 2 · VERIFICATION',
      'enter_mobile': 'Enter Mobile Number',
      'enter_mobile_hint': '9876543210',
      'send_otp': 'Send OTP',
      'otp_verification': 'Verify OTP',
      'otp_sent_to': 'Enter the 6-digit code sent to +91 ',
      'resend_otp': 'Resend OTP',
      'resend_in': 'Resend in',
      'seconds': 's',
      'otp_resent_success': 'OTP resent successfully to +91 ',
      'verify_and_continue': 'Verify & Continue',
      'invalid_otp': 'Invalid OTP. Please check the code and try again.',
      'expired_otp': 'OTP has expired. Please request a new code.',
      'too_many_attempts': 'Too many incorrect attempts. Please wait 15 minutes.',
      'farmer_onboarding_badge': 'FARMER ONBOARDING',
      'setup_profile': 'Farmer & Farm Setup',
      'setup_subtitle': 'Tell us about yourself and your primary land holding',
      'farmer_name': 'Farmer Full Name',
      'farmer_name_hint': 'e.g. Palanisamy Ramasamy',
      'farm_name': 'Farm Name',
      'farm_name_hint': 'e.g. Dharapuram Amaravathi Farm',
      'enter_name_error': 'Please enter your name',
      'enter_farm_name_error': 'Please name your farm',
      'state': 'State',
      'district': 'District',
      'village': 'Village',
      'pincode': 'PIN Code',
      'entered_area': 'Land Area',
      'entered_unit': 'Measurement Unit',
      'dpdp_consent': 'Data Privacy Consent (DPDP Act 2023)',
      'dpdp_consent_body': 'Your farm records and personal data are stored securely in Indian data centers. We never collect or store Aadhaar numbers and will not share your records without your permission.',
      'agree_and_continue': 'Agree & Continue',
      'operations': 'OPERATIONS',
      'active_holdings': 'Active Holdings',
      'active_farms': 'Active Farms',
      'cultivable_area': 'Total Area',
      'acres_total': 'Acres Total',
      'active_plots': 'Active Plots',
      'active_farms_header': 'ACTIVE REQUISITIONS / FARMS',
      'status_active': 'ACTIVE',
      'soil_water_info': 'Clay Loam · Canal & Borewell',
      'crop_paddy': 'Paddy Sambar',
      'crop_pulses': 'Pulses',
      'crop_fallow': 'Fallow',
      'plots_configured': 'Plots Configured',
      'primary': 'PRIMARY',
      'farmer': 'Farmer',
      'no_farm_selected': 'No Farm Selected',
      'no_farms_yet': 'No Farm Added Yet',
      'add_first_farm_desc': 'Add your farm details to start tracking plots, crops, and activities.',
      'add_your_first_farm': '+ Add Your Farm',
      'no_plots_configured': '0 Plots Configured',
      'add_plot_hint': 'Tap + Add Plot to map fields',
      'south_india': 'South India',
      'my_farm': 'My Farm',
      'farms_registered': 'farms registered',
      'farm_registered_singular': 'farm registered',
      'switch_farm': 'Switch Farm',
      'add_new_farm': 'Add New Farm',
      'edit_farm': 'Edit Farm',
      'edit_farm_desc': 'Update your farm details',
      'farm_updated_successfully': 'Farm updated successfully',
      'add_farm_hint': 'e.g. Mulanur Moringa Farm',
      'quick_actions': 'Quick Actions',
      'log_activity': 'Log Activity',
      'expenses': 'Expenses',
      'irrigation': 'Irrigation',
      'harvest': 'Harvest',
      'pipeline': 'Overview',
      'tasks': 'Field Logs',
      'farm_switch_title': 'Select Active Farm',
      'logout': 'Logout',
      'primary_farm': 'Primary Farm',
      'indian_mobile_label': 'Indian Mobile Number',
      'enter_otp_hint': 'Enter 6-Digit SMS Code',
      'change_mobile': 'Change Mobile',
      'sending_otp': 'Sending OTP...',
      'verifying': 'Verifying...',
      'first_time_reg': 'FIRST TIME REGISTRATION',
      'agree_and_launch': 'Agree & Launch Dashboard',
      'provisioning_account': 'Provisioning Account...',
      'district_hint': 'e.g. Tiruppur',
      'village_hint': 'e.g. Kundadam',
      'autofilled_location_hint': 'Pre-filled from registration • Editable if needed',
      'irrigation_log': 'Irrigation Log',
      'harvest_yield': 'Harvest Yield',
      'primary_holding': 'Primary Holding',
      'footer_hosted': '© 2026 Maruthamann Agricultural Systems. Stored in Indian Data Centers.',
      'unit_acre': 'Acre',
      'unit_cent': 'Cent',
      'unit_guntha': 'Guntha',
      'unit_ground': 'Ground',
      'unit_ankanam': 'Ankanam',
      'unit_hectare': 'Hectare',
      'registration_title': 'Farmer Registration',
      'registration_subtitle': 'Enter your personal and farm details to get started',
      'registration_step': 'STEP 1 OF 2 · REGISTRATION',
      'farmer_age': 'Age',
      'farmer_age_hint': 'e.g. 45',
      'taluk': 'Taluk / Tehsil',
      'taluk_hint': 'e.g. Dharapuram',
      'already_registered': 'Already have an account?',
      'login_instead': 'Sign in with Mobile',
      'new_registration': 'New Farmer Registration',
      'register_and_send_otp': 'Send Verification Code (OTP)',
      'valid_name_error': 'Please enter farmer full name',
      'valid_age_error': 'Please enter a valid age (18-99)',
      'valid_phone_error': 'Enter a valid 10-digit mobile number',
      'valid_village_error': 'Please enter your village',
      'valid_taluk_error': 'Please enter your taluk',
      'valid_district_error': 'Please enter your district',
      'new_farmer_question': 'New to Maruthamann?',
      'create_farmer_account': 'Register New Farmer Account',
      'existing_farmer_title': 'Farmer Login',
      'existing_farmer_subtitle': 'Enter your registered 10-digit mobile number',
      'phone_already_exists': 'This mobile number is already registered. Please sign in instead.',
      'sign_in_instead': 'Sign In',
      'phone_not_registered': 'This mobile number is not registered. Please register first.',
      'register_as_new_farmer': 'Register as New Farmer',
      'edit_profile_details': 'Edit Registration Details',
      'edit_profile_subtitle': 'View and update details provided during registration',
      'profile_updated_successfully': 'Profile details updated successfully',
      'verified_mobile': 'Verified Mobile Number',
      'save_changes': 'Save Changes',
      'saving': 'Saving...',
      'cancel': 'Cancel',
      'language': 'Language',
    },
    'ta': {
      'app_name': 'மருதமண்',
      'tagline': 'தென்னிந்திய விவசாயிகளுக்கான பண்ணை மேலாண்மை',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language_subtitle': 'தொடர உங்கள் விருப்பமான பிராந்திய மொழியைத் தேர்வுசெய்யவும்',
      'step_1_indicator': 'படி 1 / 2 · கைப்பேசி உள்நுழைவு',
      'step_2_indicator': 'படி 2 / 2 · சரிபார்ப்பு',
      'enter_mobile': 'கைப்பேசி எண் உள்ளிடவும்',
      'enter_mobile_hint': '9876543210',
      'send_otp': 'OTP அனுப்பவும்',
      'otp_verification': 'OTP சரிபார்ப்பு',
      'otp_sent_to': '+91 எண்ணிற்கு அனுப்பப்பட்ட 6 இலக்கக் குறியீட்டை உள்ளிடவும்: ',
      'resend_otp': 'மீண்டும் OTP அனுப்பவும்',
      'resend_in': 'மீண்டும் அனுப்ப இன்னும்',
      'seconds': 'விநாடிகள்',
      'otp_resent_success': 'OTP மீண்டும் வெற்றிகரமாக அனுப்பப்பட்டது: +91 ',
      'verify_and_continue': 'சரிபார்த்து தொடரவும்',
      'invalid_otp': 'தவறான OTP. குறியீட்டைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'expired_otp': 'OTP காலாவதியானது. புதிய குறியீட்டைக் கோரவும்.',
      'too_many_attempts': 'அதிக தவறான முயற்சிகள். 15 நிமிடங்கள் காத்திருக்கவும்.',
      'farmer_onboarding_badge': 'விவசாயி சேர்க்கை',
      'setup_profile': 'விவசாயி & பண்ணை அமைப்பு',
      'setup_subtitle': 'உங்கள் விவரங்கள் மற்றும் முதன்மைப் பண்ணைத் தகவலை வழங்கவும்',
      'farmer_name': 'விவசாயியின் முழு பெயர்',
      'farmer_name_hint': 'எ.கா. பழனிசாமி ராமசாமி',
      'farm_name': 'பண்ணையின் பெயர்',
      'farm_name_hint': 'எ.கா. தாராபுரம் அமராவதி பண்ணை',
      'enter_name_error': 'தயவுசெய்து உங்கள் பெயரை உள்ளிடவும்',
      'enter_farm_name_error': 'தயவுசெய்து உங்கள் பண்ணைக்குப் பெயரிடவும்',
      'state': 'மாநிலம்',
      'district': 'மாவட்டம்',
      'village': 'கிராமம்',
      'pincode': 'அஞ்சல் குறியீடு (PIN)',
      'entered_area': 'நிலப் பரப்பளவு',
      'entered_unit': 'அளவீட்டு அலகு (ஏக்கர், சென்ட்)',
      'dpdp_consent': 'தரவுப் பாதுகாப்பு ஒப்புதல் (DPDP சட்டம் 2023)',
      'dpdp_consent_body': 'உங்கள் பண்ணைத் தரவுகள் இந்தியத் தரவு மையங்களில் பாதுகாப்பாகச் சேமிக்கப்படுகின்றன. ஆதார் எண்கள் சேகரிக்கப்படாது; உங்கள் அனுமதியின்றி பகிரப்படாது.',
      'agree_and_continue': 'ஒப்புக்கொண்டு தொடரவும்',
      'operations': 'பண்ணை நடவடிக்கைகள்',
      'active_holdings': 'செயலில் உள்ள பண்ணைகள்',
      'active_farms': 'செயலில் உள்ள பண்ணைகள்',
      'cultivable_area': 'மொத்த பரப்பளவு',
      'acres_total': 'மொத்த ஏக்கர்',
      'active_plots': 'செயலில் உள்ள நிலப்பிரிவுகள்',
      'active_farms_header': 'செயலில் உள்ள பண்ணைகள்',
      'status_active': 'செயலில்',
      'soil_water_info': 'களிமண் வண்டல் · வாய்க்கால் & ஆழ்துளைக் கிணறு',
      'crop_paddy': 'சாம்பா நெல்',
      'crop_pulses': 'பயறு வகைகள்',
      'crop_fallow': 'தரிசு நிலம்',
      'plots_configured': 'நிலப்பிரிவுகள் உள்ளன',
      'primary': 'முதன்மை',
      'farmer': 'விவசாயி',
      'no_farm_selected': 'பண்ணை தேர்வு செய்யப்படவில்லை',
      'no_farms_yet': 'இன்னும் பண்ணை சேர்க்கப்படவில்லை',
      'add_first_farm_desc': 'நிலப்பிரிவுகள், பயிர்கள் மற்றும் செயல்பாடுகளைக் கண்காணிக்க உங்கள் பண்ணையைச் சேர்க்கவும்.',
      'add_your_first_farm': '+ உங்கள் பண்ணையைச் சேர்க்க',
      'no_plots_configured': '0 நிலப்பிரிவுகள் அமைக்கப்பட்டுள்ளன',
      'add_plot_hint': '+ நிலப்பிரிவு சேர்த்து வரைபடத்தை அமைக்கவும்',
      'south_india': 'தென்னிந்தியா',
      'my_farm': 'எனது பண்ணை',
      'farms_registered': 'பண்ணைகள் பதிவு செய்யப்பட்டுள்ளன',
      'farm_registered_singular': 'பண்ணை பதிவு செய்யப்பட்டுள்ளது',
      'switch_farm': 'பண்ணை மாற்றவும்',
      'add_new_farm': 'புதிய பண்ணை சேர்க்க',
      'edit_farm': 'பண்ணையைத் திருத்து',
      'edit_farm_desc': 'உங்கள் பண்ணை விவரங்களைப் புதுப்பிக்கவும்',
      'farm_updated_successfully': 'பண்ணை வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'add_farm_hint': 'எ.கா. மூலனூர் முருங்கை தோட்டம்',
      'quick_actions': 'விரைவுச் செயல்கள்',
      'log_activity': 'செயல் பதிவு',
      'expenses': 'செலவுகள்',
      'irrigation': 'நீர்ப்பாசனம்',
      'harvest': 'அறுவடை',
      'pipeline': 'கண்ணோட்டம்',
      'tasks': 'பண்ணைப் பதிவுகள்',
      'farm_switch_title': 'செயலில் உள்ள பண்ணையைத் தேர்வு செய்க',
      'logout': 'வெளியேறு',
      'primary_farm': 'முதன்மைப் பண்ணை',
      'indian_mobile_label': 'இந்திய கைப்பேசி எண்',
      'enter_otp_hint': '6 இலக்க SMS குறியீட்டை உள்ளிடவும்',
      'change_mobile': 'கைப்பேசி எண்ணை மாற்றவும்',
      'sending_otp': 'OTP அனுப்பப்படுகிறது...',
      'verifying': 'சரிபார்க்கப்படுகிறது...',
      'first_time_reg': 'முதல் முறை பதிவு',
      'agree_and_launch': 'ஒப்புக்கொண்டு தொடங்கவும்',
      'provisioning_account': 'கணக்கு உருவாக்கப்படுகிறது...',
      'district_hint': 'எ.கா. திருப்பூர்',
      'village_hint': 'எ.கா. குண்டடம்',
      'autofilled_location_hint': 'பதிவு விவரங்களிலிருந்து நிரப்பப்பட்டது • தேவைப்பட்டால் மாற்றலாம்',
      'irrigation_log': 'பாசனப் பதிவு',
      'harvest_yield': 'அறுவடை மகசூல்',
      'primary_holding': 'முதன்மைப் பண்ணை',
      'footer_hosted': '© 2026 மருதமண் வேளாண்மை அமைப்புகள். இந்தியத் தரவு மையங்களில் பாதுகாக்கப்படுகிறது.',
      'unit_acre': 'ஏக்கர்',
      'unit_cent': 'சென்ட்',
      'unit_guntha': 'குண்டா',
      'unit_ground': 'கிரவுண்ட்',
      'unit_ankanam': 'அங்கணம்',
      'unit_hectare': 'ஹெக்டேர்',
      'registration_title': 'விவசாயி பதிவு',
      'registration_subtitle': 'தொடங்க உங்கள் சுய மற்றும் பண்ணை விவரங்களை உள்ளிடவும்',
      'registration_step': 'படி 1 · விவசாயி பதிவு',
      'farmer_age': 'வயது',
      'farmer_age_hint': 'எ.கா. 45',
      'taluk': 'வட்டம் (தாலுகா)',
      'taluk_hint': 'எ.கா. தாராபுரம்',
      'already_registered': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'login_instead': 'கைப்பேசி மூலம் உள்நுழைக',
      'new_registration': 'புதிய விவசாயி பதிவு',
      'register_and_send_otp': 'சரிபார்ப்புக் குறியீடு அனுப்பவும் (OTP)',
      'valid_name_error': 'விவசாயியின் முழுப் பெயரை உள்ளிடவும்',
      'valid_age_error': 'சரியான வயதை உள்ளிடவும் (18-99)',
      'valid_phone_error': '10-இலக்க கைப்பேசி எண்ணை உள்ளிடவும்',
      'valid_village_error': 'உங்கள் கிராமத்தை உள்ளிடவும்',
      'valid_taluk_error': 'உங்கள் வட்டத்தை (தாலுகா) உள்ளிடவும்',
      'valid_district_error': 'உங்கள் மாவட்டத்தை உள்ளிடவும்',
      'new_farmer_question': 'மருதமண்ணிற்கு புதியவரா?',
      'create_farmer_account': 'புதிய விவசாயி கணக்கை பதிவு செய்க',
      'existing_farmer_title': 'விவசாயி உள்நுழைவு',
      'existing_farmer_subtitle': 'பதிவுசெய்த 10-இலக்க கைப்பேசி எண்ணை உள்ளிடவும்',
      'phone_already_exists': 'இந்த கைப்பேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. உள்நுழையவும்.',
      'sign_in_instead': 'உள்நுழையவும்',
      'phone_not_registered': 'இந்த கைப்பேசி எண் பதிவு செய்யப்படவில்லை. முதலில் பதிவு செய்யவும்.',
      'register_as_new_farmer': 'புதிய விவசாயியாக பதிவு செய்க',
      'edit_profile_details': 'பதிவு விவரங்களை திருத்து',
      'edit_profile_subtitle': 'பதிவின் போது வழங்கப்பட்ட விவரங்களைப் பார்த்து புதுப்பிக்கவும்',
      'profile_updated_successfully': 'சுயவிவர விவரங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன',
      'verified_mobile': 'சரிபார்க்கப்பட்ட கைப்பேசி எண்',
      'save_changes': 'மாற்றங்களை சேமிக்கவும்',
      'saving': 'சேமிக்கிறது...',
      'cancel': 'ரத்து செய்',
      'language': 'மொழி',
    },
    'te': {
      'app_name': 'మరుతమణ్',
      'tagline': 'దక్షిణ భారత రైతులకు స్మార్ట్ వ్యవసాయ రికార్డులు',
      'select_language': 'భాషను ఎంచుకోండి',
      'select_language_subtitle': 'కొనసాగడానికి మీ ప్రాధాన్య ప్రాంతీయ భాషను ఎంచుకోండి',
      'step_1_indicator': 'దశ 1 / 2 · మొబైల్ లాగిన్',
      'step_2_indicator': 'దశ 2 / 2 · ధృవీకరణ',
      'enter_mobile': 'మొబైల్ నంబర్ నమోదు చేయండి',
      'enter_mobile_hint': '9876543210',
      'send_otp': 'OTP పంపండి',
      'otp_verification': 'OTP ధృవీకరణ',
      'otp_sent_to': '+91 కు పంపిన 6 అంకెల కోడ్‌ను నమోదు చేయండి: ',
      'resend_otp': 'మళ్లీ OTP పంపండి',
      'resend_in': 'మళ్లీ పంపడానికి సమయం',
      'seconds': 'సెకన్లు',
      'otp_resent_success': 'OTP విజయవంతంగా మళ్లీ పంపబడింది: +91 ',
      'verify_and_continue': 'ధృవీకరించి కొనసాగించండి',
      'invalid_otp': 'చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.',
      'expired_otp': 'OTP గడువు ముగిసింది.',
      'too_many_attempts': 'చాలా సార్లు విఫలమైంది. 15 నిమిషాలు వేచి ఉండండి.',
      'farmer_onboarding_badge': 'రైతు నమోదు',
      'setup_profile': 'రైతు & వ్యవసాయ క్షేత్రం నమోదు',
      'setup_subtitle': 'మీ వివరాలు మరియు ప్రధాన వ్యవసాయ క్షేత్ర సమాచారం',
      'farmer_name': 'రైతు పూర్తి పేరు',
      'farmer_name_hint': 'ఉదా. పళనిసామి రామసామి',
      'farm_name': 'క్షేత్రం పేరు',
      'farm_name_hint': 'ఉదా. ధారాపురం అమరావతి ఫారమ్',
      'enter_name_error': 'దయచేసి మీ పేరును నమోదు చేయండి',
      'enter_farm_name_error': 'దయచేసి మీ ఫారమ్ పేరును నమోదు చేయండి',
      'state': 'రాష్ట్రం',
      'district': 'జిల్లా',
      'village': 'గ్రామం',
      'pincode': 'పిన్ కోడ్',
      'entered_area': 'భూమి వైశాల్యం',
      'entered_unit': 'కొలత ప్రమాణం (ఎకరాలు, గుంటలు)',
      'dpdp_consent': 'డేటా గోప్యతా సమ్మతి (DPDP చట్టం 2023)',
      'dpdp_consent_body': 'మీ సమాచారం భారతీయ డేటా సెంటర్లలో సురక్షితంగా నిల్వ చేయబడుతుంది. ఆధార్ సమాచారం సేకరించబడదు.',
      'agree_and_continue': 'అంగీకరించి కొనసాగండి',
      'operations': 'కార్యకలాపాలు',
      'active_holdings': 'యాక్టివ్ ఫారమ్‌లు',
      'active_farms': 'యాక్టివ్ ఫారమ్‌లు',
      'cultivable_area': 'మొత్తం వైశాల్యం',
      'acres_total': 'మొత్తం ఎకరాలు',
      'active_plots': 'యాక్టివ్ ప్లాట్లు',
      'active_farms_header': 'యాక్టివ్ ఫారమ్‌లు',
      'status_active': 'యాక్టివ్',
      'soil_water_info': 'బంకమట్టి నేల · కాలువ & బోర్‌వెల్',
      'crop_paddy': 'వరి (సాంబా)',
      'crop_pulses': 'పప్పుధాన్యాలు',
      'crop_fallow': 'బీడు భూమి',
      'plots_configured': 'ప్లాట్లు ఉన్నాయి',
      'primary': 'ప్రధాన',
      'farmer': 'రైతు',
      'no_farm_selected': 'ఫారమ్ ఎంచుకోలేదు',
      'no_farms_yet': 'ఇంకా పొలం జోడించబడలేదు',
      'add_first_farm_desc': 'ప్లాట్లు, పంటలు మరియు పనులను ట్రాక్ చేయడానికి మీ పొలాన్ని జోడించండి.',
      'add_your_first_farm': '+ మీ పొలాన్ని జోడించండి',
      'no_plots_configured': '0 ప్లాట్లు కాన్ఫిగర్ చేయబడ్డాయి',
      'add_plot_hint': '+ ప్లాట్ జోడించి మ్యాప్ చేయండి',
      'south_india': 'దక్షిణ భారతదేశం',
      'my_farm': 'నా ఫారమ్',
      'farms_registered': 'ఫారమ్‌లు నమోదు చేయబడ్డాయి',
      'farm_registered_singular': 'ఫారమ్ నమోదు చేయబడింది',
      'switch_farm': 'ఫారమ్ మార్చండి',
      'add_new_farm': 'కొత్త ఫారమ్ జోడించండి',
      'edit_farm': 'ఫారమ్‌ను సవరించండి',
      'edit_farm_desc': 'మీ ఫారమ్ వివరాలను నవీకరించండి',
      'farm_updated_successfully': 'ఫారమ్ విజయవంతంగా నవీకరించబడింది',
      'add_farm_hint': 'ఉదా. మూలనూరు మునగ తోట',
      'quick_actions': 'శీఘ్ర చర్యలు',
      'log_activity': 'నమోదు',
      'expenses': 'ఖర్చులు',
      'irrigation': 'నీటిపారుదల',
      'harvest': 'దిగుబడి',
      'pipeline': 'అవలోకనం',
      'tasks': 'క్షేత్ర రికార్డులు',
      'farm_switch_title': 'యాక్టివ్ ఫారమ్‌ను ఎంచుకోండి',
      'logout': 'లాగ్అవుట్',
      'primary_farm': 'ప్రధాన ఫారమ్',
      'indian_mobile_label': 'భారతీయ మొబైల్ నంబర్',
      'enter_otp_hint': '6 అంకెల SMS కోడ్ నమోదు చేయండి',
      'change_mobile': 'మొబైల్ మార్చండి',
      'sending_otp': 'OTP పంపబడుతోంది...',
      'verifying': 'ధృవీకరిస్తోంది...',
      'first_time_reg': 'మొదటి సారి నమోదు',
      'agree_and_launch': 'అంగీకరించి డాష్‌బోర్డ్ తెరవండి',
      'provisioning_account': 'ఖాతా సృష్టించబడుతోంది...',
      'district_hint': 'ఉదా. తిరుప్పూర్',
      'village_hint': 'ఉదా. కుండడం',
      'autofilled_location_hint': 'రిజిస్ట్రేషన్ వివరాల నుండి పూరించబడింది • అవసరమైతే మార్చవచ్చు',
      'irrigation_log': 'నీటిపారుదల నమోదు',
      'harvest_yield': 'దిగుబడి రికార్డు',
      'primary_holding': 'ప్రధాన క్షేత్రం',
      'footer_hosted': '© 2026 మరుతమణ్. భారతీయ డేటా సెంటర్లలో సురక్షితం.',
      'unit_acre': 'ఎకరం',
      'unit_cent': 'సెంట్',
      'unit_guntha': 'గుంట',
      'unit_ground': 'గ్రౌండ్',
      'unit_ankanam': 'అంకణం',
      'unit_hectare': 'హెక్టారు',
      'registration_title': 'రైతు నమోదు',
      'registration_subtitle': 'ప్రారంభించడానికి మీ వ్యక్తిగత మరియు వ్యవసాయ వివరాలను నమోదు చేయండి',
      'registration_step': 'దశ 1 · రైతు నమోదు',
      'farmer_age': 'వయస్సు',
      'farmer_age_hint': 'ఉదా. 45',
      'taluk': 'తాలూకా / మండలం',
      'taluk_hint': 'ఉదా. ధారాపురం',
      'already_registered': 'ఇప్పటికే ఖాతా ఉందా?',
      'login_instead': 'మొబైల్ ద్వారా లాగిన్ అవ్వండి',
      'new_registration': 'కొత్త రైతు నమోదు',
      'register_and_send_otp': 'ధృవీకరణ కోడ్ పంపండి (OTP)',
      'valid_name_error': 'దయచేసి రైతు పూర్తి పేరును నమోదు చేయండి',
      'valid_age_error': 'సరైన వయస్సు నమోదు చేయండి (18-99)',
      'valid_phone_error': '10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి',
      'valid_village_error': 'దయచేసి మీ గ్రామాన్ని నమోదు చేయండి',
      'valid_taluk_error': 'దయచేసి మీ తాలూకాను నమోదు చేయండి',
      'valid_district_error': 'దయచేసి మీ జిల్లాను నమోదు చేయండి',
      'new_farmer_question': 'మరుతమణ్‌కు కొత్తవారా?',
      'create_farmer_account': 'కొత్త రైతు ఖాతాను నమోదు చేయండి',
      'existing_farmer_title': 'రైతు లాగిన్',
      'existing_farmer_subtitle': 'నమోదిత 10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి',
      'phone_already_exists': 'ఈ మొబైల్ సంఖ్య ఇప్పటికే నమోదు చేయబడింది. దయచేసి లాగిన్ అవ్వండి.',
      'sign_in_instead': 'లాగిన్ అవ్వండి',
      'phone_not_registered': 'ఈ మొబైల్ సంఖ్య నమోదు కాలేదు. దయచేసి ముందుగా నమోదు చేయండి.',
      'register_as_new_farmer': 'కొత్త రైతుగా నమోదు చేసుకోండి',
      'edit_profile_details': 'నమోదు వివరాలను సవరించండి',
      'edit_profile_subtitle': 'నమోదు సమయంలో అందించిన వివరాలను సమీక్షించండి మరియు నవీకరించండి',
      'profile_updated_successfully': 'ప్రొఫైల్ వివరాలు విజయవంతంగా నవీకరించబడ్డాయి',
      'verified_mobile': 'ధృవీకరించబడిన మొబైల్ సంఖ్య',
      'save_changes': 'మార్పులను సేవ్ చేయండి',
      'saving': 'సేవ్ చేస్తోంది...',
      'cancel': 'రద్దు చేయండి',
      'language': 'భాష',
    },
    'kn': {
      'app_name': 'ಮರುತಮಣ್',
      'tagline': 'ದಕ್ಷಿಣ ಭಾರತೀಯ ರೈತರಿಗೆ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ದಾಖಲೆಗಳು',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_language_subtitle': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'step_1_indicator': 'ಹಂತ 1 / 2 · ಮೊಬೈಲ್ ಲಾಗಿನ್',
      'step_2_indicator': 'ಹಂತ 2 / 2 · ಪರಿಶೀಲನೆ',
      'enter_mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'enter_mobile_hint': '9876543210',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'otp_verification': 'OTP ಪರಿಶೀಲನೆ',
      'otp_sent_to': '+91 ಗೆ ಕಳುಹಿಸಲಾದ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ: ',
      'resend_otp': 'ಮತ್ತೊಮ್ಮೆ OTP ಕಳುಹಿಸಿ',
      'resend_in': 'ಮರುಕಳುಹಿಸಲು ಉಳಿದ ಸಮಯ',
      'seconds': 'ಸೆಕೆಂಡುಗಳು',
      'otp_resent_success': 'OTP ಯಶಸ್ವಿಯಾಗಿ ಮರುಕಳುಹಿಸಲಾಗಿದೆ: +91 ',
      'verify_and_continue': 'ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಯಿರಿ',
      'invalid_otp': 'ಅಮಾನ್ಯ OTP. ಪರಿಶೀಲಿಸಿ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.',
      'expired_otp': 'OTP ಅವಧಿ ಮೀರಿದೆ.',
      'too_many_attempts': 'ಹೆಚ್ಚಿನ ಪ್ರಯತ್ನಗಳು. 15 ನಿಮಿಷ ಕಾಯಿರಿ.',
      'farmer_onboarding_badge': 'ರೈತರ ನೋಂದಣಿ',
      'setup_profile': 'ರೈತ ಮತ್ತು ಕೃಷಿ ಭೂಮಿ ಸೆಟಪ್',
      'setup_subtitle': 'ನಿಮ್ಮ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ಭೂಮಿಯ ವಿವರಗಳು',
      'farmer_name': 'ರೈತರ ಪೂರ್ಣ ಹೆಸರು',
      'farmer_name_hint': 'ಉದಾ. ಪಳನಿಸ್ವಾಮಿ ರಾಮಸ್ವಾಮಿ',
      'farm_name': 'ಫಾರ್ಮ್ ಹೆಸರು',
      'farm_name_hint': 'ಉದಾ. ಧಾರಾಪುರಂ ಅಮರಾವತಿ ಫಾರ್ಮ್',
      'enter_name_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'enter_farm_name_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಜಮೀನಿನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'state': 'ರಾಜ್ಯ',
      'district': 'ಜಿಲ್ಲೆ',
      'village': 'ಗ್ರಾಮ',
      'pincode': 'ಪಿನ್ ಕೋಡ್',
      'entered_area': 'ಭೂ ವಿಸ್ತೀರ್ಣ',
      'entered_unit': 'ಅಳತೆ ಘಟಕ (ಎಕರೆ, ಗುಂಟೆ)',
      'dpdp_consent': 'ಡೇಟಾ ಗೌಪ್ಯತೆ ಸಮ್ಮತಿ (DPDP ಕಾಯಿದೆ 2023)',
      'dpdp_consent_body': 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಭಾರತೀಯ ಡೇಟಾ ಸೆಂಟರ್‌ಗಳಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಇರಿಸಲಾಗುತ್ತದೆ. ಆಧಾರ್ ಸಂಖ್ಯೆ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.',
      'agree_and_continue': 'ಒಪ್ಪಿ ಮುಂದುವರಿಯಿರಿ',
      'operations': 'ಕಾರ್ಯಾಚರಣೆಗಳು',
      'active_holdings': 'ಸಕ್ರಿಯ ಜಮೀನುಗಳು',
      'active_farms': 'ಸಕ್ರಿಯ ಜಮೀನುಗಳು',
      'cultivable_area': 'ಒಟ್ಟು ವಿಸ್ತೀರ್ಣ',
      'acres_total': 'ಒಟ್ಟು ಎಕರೆ',
      'active_plots': 'ಸಕ್ರಿಯ ಪ್ಲಾಟ್‌ಗಳು',
      'active_farms_header': 'ಸಕ್ರಿಯ ಜಮೀನುಗಳು',
      'status_active': 'ಸಕ್ರಿಯ',
      'soil_water_info': 'ಜೇಡಿಮಣ್ಣು · ಕಾಲುವೆ & ಕೊಳವೆಬಾವಿ',
      'crop_paddy': 'ಸಾಂಬಾ ಭತ್ತ',
      'crop_pulses': 'ದ್ವಿದಳ ಧಾನ್ಯಗಳು',
      'crop_fallow': 'ಬಂಜರು ಭೂಮಿ',
      'plots_configured': 'ಪ್ಲಾಟ್‌ಗಳು ಸಿದ್ಧವಾಗಿವೆ',
      'primary': 'ಪ್ರಾಥಮಿಕ',
      'farmer': 'ರೈತ',
      'no_farm_selected': 'ಯಾವುದೇ ಜಮೀನು ಆಯ್ಕೆಯಾಗಿಲ್ಲ',
      'no_farms_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಫಾರ್ಮ್ ಸೇರಿಸಲಾಗಿಲ್ಲ',
      'add_first_farm_desc': 'ಪ್ಲಾಟ್‌ಗಳು, ಬೆಳೆಗಳು ಮತ್ತು ಚಟುವಟಿಕೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಫಾರ್ಮ್ ಸೇರಿಸಿ.',
      'add_your_first_farm': '+ ನಿಮ್ಮ ಫಾರ್ಮ್ ಸೇರಿಸಿ',
      'no_plots_configured': '0 ಪ್ಲಾಟ್‌ಗಳು ಕಾನ್ಫಿಗರ್ ಮಾಡಲಾಗಿದೆ',
      'add_plot_hint': '+ ಪ್ಲಾಟ್ ಸೇರಿಸಿ ನಕ್ಷೆ ಮಾಡಿ',
      'south_india': 'ದಕ್ಷಿಣ ಭಾರತ',
      'my_farm': 'ನನ್ನ ಜಮೀನು',
      'farms_registered': 'ಜಮೀನುಗಳು ನೋಂದಾಯಿಸಲಾಗಿದೆ',
      'farm_registered_singular': 'ಜಮೀನು ನೋಂದಾಯಿಸಲಾಗಿದೆ',
      'switch_farm': 'ಜಮೀನು ಬದಲಾಯಿಸಿ',
      'add_new_farm': 'ಹೊಸ ಫಾರ್ಮ್ ಸೇರಿಸಿ',
      'edit_farm': 'ಫಾರ್ಮ್ ಸಂಪಾದಿಸಿ',
      'edit_farm_desc': 'ನಿಮ್ಮ ಫಾರ್ಮ್ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ',
      'farm_updated_successfully': 'ಫಾರ್ಮ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
      'add_farm_hint': 'ಉದಾ. ಮೂಲನೂರು ನುಗ್ಗೆ ತೋಟ',
      'quick_actions': 'ತ್ವರಿತ ಕಾರ್ಯಗಳು',
      'log_activity': 'ದಾಖಲೆ',
      'expenses': 'ವೆಚ್ಚಗಳು',
      'irrigation': 'ನೀರಾವರಿ',
      'harvest': 'ಕೊಯ್ಲು',
      'pipeline': 'ಅವಲೋಕನ',
      'tasks': 'ಕ್ಷೇತ್ರ ದಾಖಲೆಗಳು',
      'farm_switch_title': 'ಸಕ್ರಿಯ ಜಮೀನು ಆಯ್ಕೆಮಾಡಿ',
      'logout': 'ನಿರ್ಗಮಿಸಿ',
      'primary_farm': 'ಪ್ರಾಥಮಿಕ ಜಮೀನು',
      'indian_mobile_label': 'ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'enter_otp_hint': '6 ಅಂಕಿಯ SMS ಕೋಡ್ ನಮೂದಿಸಿ',
      'change_mobile': 'ಮೊಬೈಲ್ ಬದಲಾಯಿಸಿ',
      'sending_otp': 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
      'verifying': 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
      'first_time_reg': 'ಮೊದಲ ಬಾರಿಗೆ ನೋಂದಣಿ',
      'agree_and_launch': 'ಒಪ್ಪಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯಿರಿ',
      'provisioning_account': 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
      'district_hint': 'ಉದಾ. ತಿರುಪ್ಪೂರು',
      'village_hint': 'ಉದಾ. ಕುಂಡಡಂ',
      'autofilled_location_hint': 'ನೋಂದಣಿ ವಿವರಗಳಿಂದ ತುಂಬಲಾಗಿದೆ • ಅಗತ್ಯವಿದ್ದರೆ ಬದಲಾಯಿಸಬಹುದು',
      'irrigation_log': 'ನೀರಾವರಿ ದಾಖಲೆ',
      'harvest_yield': 'ಕೊಯ್ಲು ಇಳುವರಿ',
      'primary_holding': 'ಪ್ರಾಥಮಿಕ ಜಮೀನು',
      'footer_hosted': '© 2026 ಮರುತಮಣ್. ಭಾರತೀಯ ಡೇಟಾ ಕೇಂದ್ರಗಳಲ್ಲಿ ಸುರಕ್ಷಿತ.',
      'unit_acre': 'ಎಕರೆ',
      'unit_cent': 'ಸೆಂಟ್',
      'unit_guntha': 'ಗುಂಟೆ',
      'unit_ground': 'ಗ್ರೌಂಡ್',
      'unit_ankanam': 'ಅಂಕಣ',
      'unit_hectare': 'ಹೆಕ್ಟೇರ್',
      'registration_title': 'ರೈತರ ನೋಂದಣಿ',
      'registration_subtitle': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮತ್ತು ಕೃಷಿ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
      'registration_step': 'ಹಂತ 1 · ರೈತರ ನೋಂದಣಿ',
      'farmer_age': 'ವಯಸ್ಸು',
      'farmer_age_hint': 'ಉದಾ. 45',
      'taluk': 'ತಾಲೂಕು',
      'taluk_hint': 'ಉದಾ. ಧಾರಾಪುರಂ',
      'already_registered': 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
      'login_instead': 'ಮೊಬೈಲ್ ಮೂಲಕ ಲಾಗಿನ್ ಆಗಿ',
      'new_registration': 'ಹೊಸ ರೈತರ ನೋಂದಣಿ',
      'register_and_send_otp': 'ಪರಿಶೀಲನಾ ಕೋಡ್ ಕಳುಹಿಸಿ (OTP)',
      'valid_name_error': 'ದಯವಿಟ್ಟು ರೈತರ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'valid_age_error': 'ಸರಿಯಾದ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ (18-99)',
      'valid_phone_error': '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'valid_village_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಗ್ರಾಮವನ್ನು ನಮೂದಿಸಿ',
      'valid_taluk_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ತಾಲೂಕನ್ನು ನಮೂದಿಸಿ',
      'valid_district_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಜಿಲ್ಲೆಯನ್ನು ನಮೂದಿಸಿ',
      'new_farmer_question': 'ಮರುತಮಣ್‌ಗೆ ಹೊಸಬರೇ?',
      'create_farmer_account': 'ಹೊಸ ರೈತರ ಖಾತೆಯನ್ನು ನೋಂದಾಯಿಸಿ',
      'existing_farmer_title': 'ರೈತರ ಲಾಗಿನ್',
      'existing_farmer_subtitle': 'ನೋಂದಾಯಿತ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'phone_already_exists': 'ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿದೆ. ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
      'sign_in_instead': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'phone_not_registered': 'ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ನೋಂದಾಯಿಸಿ.',
      'register_as_new_farmer': 'ಹೊಸ ರೈತರಾಗಿ ನೋಂದಾಯಿಸಿ',
      'edit_profile_details': 'ನೋಂದಣಿ ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ',
      'edit_profile_subtitle': 'ನೋಂದಣಿ ಸಮಯದಲ್ಲಿ ಒದಗಿಸಿದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನವೀಕರಿಸಿ',
      'profile_updated_successfully': 'ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
      'verified_mobile': 'ದೃಢೀಕರಿಸಿದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      'saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'language': 'ಭಾಷೆ',
    },
    'ml': {
      'app_name': 'മരുതമൺ',
      'tagline': 'ദക്ഷിണേന്ത്യൻ കർഷകർക്കായി സ്മാർട്ട് കൃഷി വിവരങ്ങൾ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'select_language_subtitle': 'തുടരുന്നതിന് നിങ്ങളുടെ പ്രാദേശിക ഭാഷ തിരഞ്ഞെടുക്കുക',
      'step_1_indicator': 'ഘട്ടം 1 / 2 · മൊബൈൽ ലോഗിൻ',
      'step_2_indicator': 'ഘട്ടം 2 / 2 · പരിശോധന',
      'enter_mobile': 'മൊബൈൽ നമ്പർ നൽകുക',
      'enter_mobile_hint': '9876543210',
      'send_otp': 'OTP അയക്കുക',
      'otp_verification': 'OTP സ്ഥിരീകരണം',
      'otp_sent_to': '+91 ലേക്ക് അയച്ച 6 അക്ക കോഡ് നൽകുക: ',
      'resend_otp': 'വീണ്ടും OTP അയക്കുക',
      'resend_in': 'വീണ്ടും അയക്കാൻ ബാക്കി',
      'seconds': 'സെക്കന്റുകൾ',
      'otp_resent_success': 'OTP വിജയകരമായി വീണ്ടും അയച്ചു: +91 ',
      'verify_and_continue': 'സ്ഥിരീകരിച്ച് തുടരുക',
      'invalid_otp': 'തെറ്റായ OTP. വീണ്ടും ശ്രമിക്കുക.',
      'expired_otp': 'OTP കാലാവധി കഴിഞ്ഞു.',
      'too_many_attempts': 'കൂടുതൽ തെറ്റായ ശ്രമങ്ങൾ. 15 മിനിറ്റ് കാത്തിരിക്കുക.',
      'farmer_onboarding_badge': 'കർഷക രജിസ്ട്രേഷൻ',
      'setup_profile': 'കർഷകന്റെയും കൃഷിയിടത്തിന്റെയും വിവരങ്ങൾ',
      'setup_subtitle': 'നിങ്ങളുടെയും പ്രാഥമിക കൃഷിഭൂമിയുടെയും വിവരങ്ങൾ നൽകുക',
      'farmer_name': 'കർഷകന്റെ മുഴുവൻ പേര്',
      'farmer_name_hint': 'ഉദാ. പളനിസാമി രാമസാമി',
      'farm_name': 'ഫാമിന്റെ പേര്',
      'farm_name_hint': 'ഉദാ. ധാരാപുരം അമരാവതി ഫാം',
      'enter_name_error': 'ദയവായി നിങ്ങളുടെ പേര് നൽകുക',
      'enter_farm_name_error': 'ദയവായി നിങ്ങളുടെ ഫാമിന്റെ പേര് നൽകുക',
      'state': 'സംസ്ഥാനം',
      'district': 'ജില്ല',
      'village': 'ഗ്രാമം',
      'pincode': 'പിൻ കോഡ്',
      'entered_area': 'വിസ്തീർണം',
      'entered_unit': 'അളവ് യൂണിറ്റ് (സെന്റ്, ഏക്കർ)',
      'dpdp_consent': 'ഡാറ്റ സ്വകാര്യത സമ്മതം (DPDP ആക്ട് 2023)',
      'dpdp_consent_body': 'നിങ്ങളുടെ വിവരങ്ങൾ ഇന്ത്യൻ ഡാറ്റാ കേന്ദ്രങ്ങളിൽ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു. ആധാർ വിവരങ്ങൾ ശേഖരിക്കില്ല.',
      'agree_and_continue': 'സമ്മതിച്ച് തുടരുക',
      'operations': 'പ്രവർത്തനങ്ങൾ',
      'active_holdings': 'സജീവ ഫാമുകൾ',
      'active_farms': 'സജീവ ഫാമുകൾ',
      'cultivable_area': 'ആകെ വിസ്തീർണ്ണം',
      'acres_total': 'ആകെ ഏക്കർ',
      'active_plots': 'സജീവ പ്ലോട്ടുകൾ',
      'active_farms_header': 'സജീവ ഫാമുകൾ',
      'status_active': 'സജീവം',
      'soil_water_info': 'കളിമണ്ണ് · കനാൽ & കുഴൽക്കിണർ',
      'crop_paddy': 'സാംബ നെല്ല്',
      'crop_pulses': 'പയറുവർഗ്ഗങ്ങൾ',
      'crop_fallow': 'തരിശുഭൂമി',
      'plots_configured': 'പ്ലോട്ടുകൾ ക്രമീകരിച്ചു',
      'primary': 'പ്രാഥമികം',
      'farmer': 'കർഷകൻ',
      'no_farm_selected': 'ഫാം തിരഞ്ഞെടുത്തിട്ടില്ല',
      'no_farms_yet': 'ഫാം ഇതുവരെ ചേർത്തിട്ടില്ല',
      'add_first_farm_desc': 'പ്ലോട്ടുകളും വിളകളും പ്രവർത്തനങ്ങളും ട്രാക്ക് ചെയ്യാൻ നിങ്ങളുടെ ഫാം ചേർക്കുക.',
      'add_your_first_farm': '+ നിങ്ങളുടെ ഫാം ചേർക്കുക',
      'no_plots_configured': '0 പ്ലോട്ടുകൾ ക്രമീകരിച്ചു',
      'add_plot_hint': '+ പ്ലോട്ട് ചേർത്ത് മാപ്പ് ചെയ്യുക',
      'south_india': 'ദക്ഷിണേന്ത്യ',
      'my_farm': 'എന്റെ ഫാം',
      'farms_registered': 'ഫാമുകൾ രജിസ്റ്റർ ചെയ്തു',
      'farm_registered_singular': 'ഫാം രജിസ്റ്റർ ചെയ്തു',
      'switch_farm': 'ഫാം മാറ്റുക',
      'add_new_farm': 'പുതിയ ഫാം ചേർക്കുക',
      'edit_farm': 'ഫാം എഡിറ്റ് ചെയ്യുക',
      'edit_farm_desc': 'നിങ്ങളുടെ ഫാം വിവരങ്ങൾ പുതുക്കുക',
      'farm_updated_successfully': 'ഫാം വിജയകരമായി പുതുക്കി',
      'add_farm_hint': 'ഉദാ. മൂലനൂർ മുരിങ്ങ തോപ്പ്',
      'quick_actions': 'ദ്രുത നടപടികൾ',
      'log_activity': 'രേഖപ്പെടുത്തുക',
      'expenses': 'ചെലവുകൾ',
      'irrigation': 'ജലസേചനം',
      'harvest': 'വിളവെടുപ്പ്',
      'pipeline': 'അവലോകനം',
      'tasks': 'ഫീൽഡ് ലോഗുകൾ',
      'farm_switch_title': 'സജീവ ഫാം തിരഞ്ഞെടുക്കുക',
      'logout': 'ലോഗ് ഔട്ട്',
      'primary_farm': 'പ്രാഥമിക ഫാം',
      'indian_mobile_label': 'ഇന്ത്യൻ മൊബൈൽ നമ്പർ',
      'enter_otp_hint': '6 അക്ക SMS കോഡ് നൽകുക',
      'change_mobile': 'മൊബൈൽ മാറ്റുക',
      'sending_otp': 'OTP അയയ്ക്കുന്നു...',
      'verifying': 'പരിശോധിക്കുന്നു...',
      'first_time_reg': 'ആദ്യ രജിസ്ട്രേഷൻ',
      'agree_and_launch': 'സമ്മതിച്ച് ഡാഷ്‌ബോർഡ് തുറക്കുക',
      'provisioning_account': 'അക്കൗണ്ട് നിർമ്മിക്കുന്നു...',
      'district_hint': 'ഉദാ. തിരുപ്പൂർ',
      'village_hint': 'ഉദാ. കുണ്ടടം',
      'autofilled_location_hint': 'രജിസ്ട്രേഷൻ വിവരങ്ങളിൽ നിന്ന് പൂരിപ്പിച്ചത് • ആവശ്യമെങ്കിൽ മാറ്റാം',
      'irrigation_log': 'ജലസേചന രേഖ',
      'harvest_yield': 'വിളവെടുപ്പ് അളവ്',
      'primary_holding': 'പ്രാഥമിക കൃഷിയിടം',
      'footer_hosted': '© 2026 മരുതമൺ. ഇന്ത്യൻ ഡാറ്റാ കേന്ദ്രങ്ങളിൽ സുരക്ഷിതം.',
      'unit_acre': 'ഏക്കർ',
      'unit_cent': 'സെന്റ്',
      'unit_guntha': 'ഗുന്ത',
      'unit_ground': 'ഗ്രൗണ്ട്',
      'unit_ankanam': 'അങ്കണം',
      'unit_hectare': 'ഹെക്ടർ',
      'registration_title': 'കർഷക രജിസ്ട്രേഷൻ',
      'registration_subtitle': 'ആരംഭിക്കുന്നതിന് നിങ്ങളുടെ വ്യക്തിഗത, കാർഷിക വിവരങ്ങൾ നൽകുക',
      'registration_step': 'ഘട്ടം 1 · കർഷക രജിസ്ട്രേഷൻ',
      'farmer_age': 'പ്രായം',
      'farmer_age_hint': 'ഉദാ. 45',
      'taluk': 'താലൂക്ക്',
      'taluk_hint': 'ഉദാ. ധാരാപുരം',
      'already_registered': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
      'login_instead': 'മൊബൈൽ വഴി ലോഗിൻ ചെയ്യുക',
      'new_registration': 'പുതിയ കർഷക രജിസ്ട്രേഷൻ',
      'register_and_send_otp': 'സ്ഥിരീകരണ കോഡ് അയയ്ക്കുക (OTP)',
      'valid_name_error': 'ദയവായി കർഷകന്റെ പൂർണ്ണ നാമം നൽകുക',
      'valid_age_error': 'ശരിയായ പ്രായം നൽകുക (18-99)',
      'valid_phone_error': '10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
      'valid_village_error': 'ദയവായി നിങ്ങളുടെ ഗ്രാമം നൽകുക',
      'valid_taluk_error': 'ദയവായി നിങ്ങളുടെ താലൂക്ക് നൽകുക',
      'valid_district_error': 'ദയവായി നിങ്ങളുടെ ജില്ല നൽകുക',
      'new_farmer_question': 'മരുതമണ്ണിലേക്ക് പുതിയതാണോ?',
      'create_farmer_account': 'പുതിയ കർഷക അക്കൗണ്ട് രജിസ്റ്റർ ചെയ്യുക',
      'existing_farmer_title': 'കർഷക ലോഗിൻ',
      'existing_farmer_subtitle': 'രജിസ്റ്റർ ചെയ്ത 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
      'phone_already_exists': 'ഈ മൊബൈൽ നമ്പർ ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്. ദയവായി ലോഗിൻ ചെയ്യുക.',
      'sign_in_instead': 'ലോഗിൻ ചെയ്യുക',
      'phone_not_registered': 'ഈ മൊബൈൽ നമ്പർ രജിസ്റ്റർ ചെയ്തിട്ടില്ല. ദയവായി ആദ്യം രജിസ്റ്റർ ചെയ്യുക.',
      'register_as_new_farmer': 'പുതിയ കർഷകനായി രജിസ്റ്റർ ചെയ്യുക',
      'edit_profile_details': 'രജിസ്ട്രേഷൻ വിവരങ്ങൾ തിരുത്തുക',
      'edit_profile_subtitle': 'രജിസ്ട്രേഷൻ സമയത്ത് നൽകിയ വിവരങ്ങൾ പരിശോധിച്ച് പുതുക്കുക',
      'profile_updated_successfully': 'പ്രൊഫൈൽ വിവരങ്ങൾ വിജയകരമായി പുതുക്കി',
      'verified_mobile': 'സ്ഥിരീകരിച്ച മൊബൈൽ നമ്പർ',
      'save_changes': 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
      'saving': 'സംരക്ഷിക്കുന്നു...',
      'cancel': 'റദ്ദാക്കുക',
      'language': 'ഭാഷ',
    },
  };

  String tr(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String translateUnit(String unit) {
    final clean = unit.toLowerCase().trim();
    return tr('unit_$clean');
  }

  String translateState(String stateCode) {
    final langCode = locale.languageCode;
    final Map<String, Map<String, String>> stateNames = {
      'TN': {
        'ta': 'தமிழ்நாடு',
        'te': 'తమిళనాడు',
        'kn': 'ತಮಿಳುನಾಡು',
        'ml': 'തമിഴ്‌നാട്',
        'en': 'Tamil Nadu',
      },
      'AP': {
        'ta': 'ஆந்திரப் பிரதேசம்',
        'te': 'ఆంధ్రప్రదేశ్',
        'kn': 'ಆಂಧ್ರಪ್ರದೇಶ',
        'ml': 'ആന്ധ്രാപ്രദേശ്',
        'en': 'Andhra Pradesh',
      },
      'TG': {
        'ta': 'தெலங்கானா',
        'te': 'తెలంగాణ',
        'kn': 'ತೆಲಂಗಾಣ',
        'ml': 'തെലങ്കാന',
        'en': 'Telangana',
      },
      'KA': {
        'ta': 'கர்நாடகா',
        'te': 'కర్ణాటక',
        'kn': 'ಕರ್ನಾಟಕ',
        'ml': 'കർണാടക',
        'en': 'Karnataka',
      },
      'KL': {
        'ta': 'கேரளா',
        'te': 'కేరళ',
        'kn': 'ಕೇರಳ',
        'ml': 'കേരളം',
        'en': 'Kerala',
      },
      'PY': {
        'ta': 'புதுச்சேரி',
        'te': 'పుదుచ్చేరి',
        'kn': 'ಪುದುಚೇರಿ',
        'ml': 'പുതുച്ചേരി',
        'en': 'Puducherry',
      },
    };
    return stateNames[stateCode]?[langCode] ?? stateNames[stateCode]?['en'] ?? stateCode;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ta', 'te', 'kn', 'ml'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
